FEATURE_FLAG = {
    "EMBEDDED_SUPERSET": True,
 }
ENABLE_PROXY_FIX = True
SESSION_COOKIE_SAMESITE = None

PUBLIC_ROLE_LIKE_GAMMA = True
#AUTH_ROLE_PUBLIC = ’GAMMA’

WTF_CSRF_ENABLED = False
TALISMAN_ENABLED = False

HTTP_HEADERS = {’X-Frame-Options’: ’ALLOWALL’}
